### ISSUE TITLE
[1.12.2]Unable to launch

### ISSUE THREAD

**Issue by ghost** [glowredman/TX-Loader#3]
Tested with only this mod,here is the logs
debug.log:https://mclo.gs/LQXT6LR
latest.log:https://mclo.gs/oV4SOyO

**Comment by Lonelyxiya** [comment]
Yes, I had the same problem

**Comment by glowredman** [comment]
Strange. I'll have a look later

**Comment by glowredman** [comment]
Should be fixed now. https://modrinth.com/mod/tx-loader/version/1.12.2-1.5.1
