### ISSUE TITLE
ModularMachinery-Community-Edition And tx loader Unable to resolve texture loss issue

### ISSUE THREAD

**Issue by Lonelyxiya** [glowredman/TX-Loader#5]
![image](https://github.com/glowredman/TX-Loader/assets/83713575/7eebd2c2-25e9-439e-8219-974aed9fd97a)
To translate the Chinese into English, after installing ResourceLoader, create a "models" folder and a "textures" folder in your .minecraft\resources\modularmachinery directory. Inside the "models" folder, create an empty folder named "block". Inside the "textures" folder, create a folder named "blocks". This can solve the issue of the controller turning into a purple block.

After repeatedly using its method, I found that the "tx loader" does not have a modid. This prevents the texture issue from being fixed. It would be great if you could make this mod compatible with.

![image](https://github.com/glowredman/TX-Loader/assets/83713575/70fd924f-f05f-4876-bcf7-0d67fa2eaf8c)
![image](https://github.com/glowredman/TX-Loader/assets/83713575/cc08abc9-b8dd-4bad-b935-02ff436934d7)

Github mmce mod: https://github.com/KasumiNova/ModularMachinery-Community-Edition

**Comment by glowredman** [comment]
Works for me. Did you actually create the model files and not just their directories?

**Comment by Lonelyxiya** [comment]
Yes,I see MMCE Chinese encyclopedia to solve the texture loss problem, but I follow config/txloader/load/modularmachinery directory to try to solve, but no effect.

**Comment by Lonelyxiya** [comment]
https://github.com/KasumiNova/ModularMachinery-Community-Edition/commit/abd667adbd76ca0df59062035e2189ec174bb298
Fixed
